name: Build and push backend container to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Clean maven
      working-directory: ./backend
      run: mvn clean
    - name: Build with Maven
      working-directory: ./backend
      run: mvn package -Dmaven.test.skip=true
      
      
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      working-directory: ./backend
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      working-directory: ./backend
      run: heroku container:push -a ${{ secrets.HEROKU_BACKEND_APP_NAME }} web
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      working-directory: ./backend
      run: heroku container:release -a ${{ secrets.HEROKU_BACKEND_APP_NAME }} web
